#CI项目名
name: 构建玩客云迷你版IMAGES

on:
  #自动编译：每天早上4点
  #schedule:
    #- cron: 0 20 * * *
  #手动编译
  workflow_dispatch:

#CI权限
permissions: write-all

#CI任务
jobs:
  owrt_config:
    #调用公用编译核心OWRT-CORE.yml
    uses: ./.github/workflows/OWRT-CORE-OneCloud.yml
    with:
      #编译平台，X64包含X86,arm
      OWRT_TARGET: meson8b
      #默认主题
      OWRT_THEME: argon
      #默认主机名
      OWRT_NAME: OneCloud
      #默认密码，仅作展示，更改无效
      OWRT_PW: password
      #默认地址
      OWRT_IP: 192.168.1.110
      #默认源码
      OWRT_URL: https://github.com/coolsnowwolf/lede
      #源码版本
      OWRT_BRANCH: master
      #自定义config
      OWRT_CFG: arm7_mini.config
      #设备类型
      OWRT_TYPE: OneCloud-Mini
      OWRT_LINUX: 6.1.62
      OWRT_FILES: onecloud/files
      DIY_P1_SH: mo_app.sh
      DIY_P2_SH: lean2.sh